---
title: "raw_to_clean"
output: html_document
date: "2025-04-23"
---

## Control under pressure — the influence of aversive motivation on adaptive control

## Raw to clean

## Loading packages

```{r}
if(!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)
library(dplyr)
library(stringr)
```

## Loading raw data

```{r}
raw_data <- read.csv("pilotresults.csv")
```

## flagging previous events in probe stimuli before filtering
```{r}
raw_data = raw_data %>% 
  mutate(feedback = case_when(grepl(">✘</div>",stimulus) ~ "visual_punishment", # flagging different feedback events in new variable
                                grepl("&#11036", stimulus) ~ "neutral",
                                grepl(">✘<br>5 garast veszítettél</div>",stimulus) ~ "monetary_loss",
                                grepl("✔",stimulus) ~ "tickmark"
                                ),
         prev_feedback = ifelse(task=="probe", lag(feedback,n=4),""), ## Flagging previous feedback in probe trial
         prev_loss = ifelse(prev_feedback == "monetary_loss", 1,0), ## Flagging if monetary loss happened before this probe 
         prev_correct = lag(correct,n=5), ## flagging previous correct
         prev_congruency = lag(congruency, n=5), ## creating previous congruency variable
         block_feedback_type = lead(feedback_type)) ## moving feedback type data to probe variable



```


## Cleaning/filtering data

```{r}
#Filtering columns
processed_data = raw_data %>% 
  select(-trial_type,
         -trial_index,
         -plugin_version,
         -success,
         -question_order,
         -slider_start,
         -stimulus,
         -time_elapsed)

#raw_data_filtered <- raw_data_filtered %>%
 # filter(
  #  feedback_type %in% c(
   #   "random_punishment_random",
    #  "no_punishment_incongruent",
     # "no_punishment_congruent",
      #"punishment_incongruent",
    #  "punishment_congruent"
    #) |
    #response %in% c("n", "j", "f", "g"))
processed_data = raw_data %>% # Keeping only probe rows
  filter(task=="probe")

processed_data = processed_data %>% 
  filter(name != "practice")

processed_data =processed_data %>% ## filtering out first trials here 
  filter(!is.na(prev_feedback))

processed_rt_data = processed_data %>% ## keeping only correct responses for rt analysis
  filter(correct == "true",
         prev_correct == "true")

#True/false values to 1/0

#raw_data_labeled = raw_data_labeled %>%
 # mutate(
 #   correct = factor(recode(correct,
 #                            "true" = "1",
  #                           "false" = "0")))

#task_trials <- raw_data_labeled %>%
 # filter(response %in% c("n", "j", "f", "g")) %>%
  #select(-feedback_type) %>%
  #rename(feedback_type = feedback_from_next)
```

## example plot for cse
```{r}
cse_summary_table = processed_rt_data %>% 
  group_by(prev_congruency, congruency) %>% 
  summarize(N = n(),
            mean_rt = mean(as.numeric(rt), na.rm = T),
            sd_rt = sd(rt, na.rm = T),
            se_rt = sd_rt/sqrt(N))

```
```{r}
cseplot = cse_summary_table %>% 
  ggplot()+
  aes(x=prev_congruency, y=mean_rt, color=congruency, group=congruency)+
  geom_point(size=1)+
  geom_path(size=1)+
  geom_errorbar(aes(ymin=mean_rt-se_rt, ymax=mean_rt+se_rt), width=.2, size=1)+
  scale_color_brewer(palette = "Pastel2")+
  papaja::theme_apa()

cseplot
```




## Demography data

```{r}
demography_data <- raw_data %>%
  filter(
    trial_type %in% c(
      "survey-text",
      "survey-multi-choice"))
    
demography_data <- demography_data %>%
  select(
    response,
    subj_code
  )

demography_data <- demography_data %>%
  mutate(
    age = str_extract(response, '"age":"\\d+"') %>%
      str_extract("\\d+") %>%
      as.numeric(),
    
    education = str_extract(response, '"education":"[^"]+"') %>%
      str_remove_all('"education":"') %>%
      str_remove('"'),
    
    gender = str_extract(response, '"gender":"[^"]+"') %>%
      str_remove_all('"gender":"') %>%
      str_remove('"')
  )

demography_data <- demography_data %>%
  select(-response)

demography_data <- demography_data %>%
  group_by(subj_code) %>%
  summarize(
    age = coalesce(age[1], age[2]),
    education = coalesce(education[1], education[2]),
    gender = coalesce(gender[1], gender[2])
  )
```



## Survey data

```{r}
#Survey data

#PANAS data

panas_data = raw_data %>% 
  filter( trial_type == "survey-likert")

panas_data = panas_data %>%
  select(-rt,
         -stimulus,
         -trial_index,
         -plugin_version,
         -time_elapsed,
         -success,
         -question_order,
         -task,
         -correct_response,
         -congruency,
         -name,
         -correct,
         -slider_start,
         -feedback_type,
         -trial_type)

panas_data <- panas_data %>%
  mutate(
    item = str_extract(response, '"(.*?)"') %>% str_remove_all('"'),
    value = str_extract(response, ':\\d+') %>% str_remove(':') %>% as.numeric()
  ) %>%
  select(item, value, subj_code)

#VAS dislike data

dislike_data = raw_data %>% 
  filter( trial_type == "html-slider-response",
          stimulus != "<p>Kérlek, jelöld be 0 (egyáltalán nem) és 100 (teljes mértékben) között, hogy milyen mértékben vettél észre szabályosságot a visszajelzések bemutatásában!</p>")

dislike_data = dislike_data %>%
  select(-rt,
         -stimulus,
         -trial_index,
         -plugin_version,
         -time_elapsed,
         -success,
         -question_order,
         -task,
         -correct_response,
         -congruency,
         -name,
         -correct,
         slider_start,
         -feedback_type,
         -trial_type)

#VAS manipulation data

manipulation_data = raw_data %>% 
  filter( trial_type == "html-slider-response",
          stimulus == "<p>Kérlek, jelöld be 0 (egyáltalán nem) és 100 (teljes mértékben) között, hogy milyen mértékben vettél észre szabályosságot a visszajelzések bemutatásában!</p>")

manipulation_data = manipulation_data %>%
  select(-rt,
         -stimulus,
         -trial_index,
         -plugin_version,
         -time_elapsed,
         -success,
         -question_order,
         -task,
         -correct_response,
         -congruency,
         -name,
         -correct,
         slider_start,
         -feedback_type,
         -trial_type)
```
